import type { Metadata } from 'next'
import { Chivo as FontSans } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import { ReactNode } from 'react'
import { Toaster } from 'react-hot-toast'

import TanstackProvider from '@/providers/tanstack-provider'
import ThemeProvider from '@/providers/theme-provider'
import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'NAEE - Home page',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: ReactNode
}>) => {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={fontSans.className}>
        <NextTopLoader color='red' height={2} showSpinner={false} shadow={false} />
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <TanstackProvider>
            {children}
            <Toaster position='top-center' />
          </TanstackProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
