import type { Metadata } from "next";
import { Roboto as FontSans } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "NAEE - Home page",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontSans.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
